name: Build

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - develop
      - staging
      - main

concurrency:
  group: environment-${{github.ref}}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '1.8'
        distribution: 'microsoft'
        cache: maven
    - name: Build
      run: mvn -B package --file pom.xml
