name: Build and Run code analysis

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - develop
      - staging
      - main

concurrency:
  group: environment-${{github.ref}}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
        
    - name: Build
      run: mvn -B clean package
  
  analyze:
    name: Run Code Analysis
    needs: build
    uses: ./.github/workflows/code-analysis.yaml
