name: Build

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - develop
      - staging
      - main

concurrency:
  group: environment-${{github.ref}}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Java JDK
      uses: actions/setup-java@v1.4.4
      with:
        java-version: 1.8
        java-package: jdk
    - name: Build
      run: mvn package --file pom.xml
