name: Build

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - develop
      - staging
      - main

concurrency:
  group: environment-${{github.ref}}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: mvnw package
