name: Deploy pipeline

on:
  push:
    branches:
      - 'develop'
      - 'staging'
      - 'main'

jobs:
  build-and-analyze:
    uses: ./.github/workflows/build-and-analyze.yaml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker-push:
    runs-on: ubuntu-latest
    needs: build-and-analyze
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/products-service:latest
  
  deploy:
    runs-on: ubuntu-latest
    env:
      EKS-CLUSTER-SUFFIX: ${{ github.ref_name == 'main' && 'production' || github.ref_name == 'staging' && 'staging' || github.ref == 'develop' && 'dev' }}
    needs: docker-push
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.3
      with:
        repository: practicodevops/practico-devops-infrastructure
        ref: main
        token: Personal access token generado de la organizacion
        path: kubernetes
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    # Install kubectl and helm
    
    - name: Configure Kubernetes context
      run: |
        aws eks update-kubeconfig --name eks-cluster-${{ env.EKS-CLUSTER-SUFFIX }} --region us-east-1

    - name: Deploy to EKS
      run: |
        kubectl apply -f ingress.yaml
        helm upgrade --install products ./products-service