name: Postman testing

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/products-service-test:latest

  postman-testing:
    name: Postman testing
    runs-on: ubuntu-latest
    needs: build-image
    container:
      image: ${{ secrets.DOCKERHUB_USERNAME }}/products-service-test:latest
      volumes:
        - products-service.postman_collection.json:/app

    steps: 
    - name: Install Node
      uses: actions/checkout@v3
      with:
        node-version: "17.x"

    - name: Install newman
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra

    - name: Make Directory for results
      run: mkdir result

    - name: Test
      run: curl localhost:8080/products
    # - name: Run POSTMAN collection
    #   run: |
    #     newman run "products-service.postman_collection.json" -r htmlextra --reporter-htmlextra-export result/report.html

    # - name: Output the run Details
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: Reports
    #     path: result