name: Postman testing

on:
  workflow_call:
    secrets:
      EKS_URL:
        required: true

jobs:
  postman-testing:
    name: Postman testing
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v3

    - name: Install Node
      uses: actions/checkout@v3
      with:
        node-version: "17.x"

    - name: Install newman
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra

    - name: Make Directory for results
      run: mkdir result

    - name: Install more-utils
      run: sudo apt-get install moreutils

    - name: Update Collection JSON with EKS Url
      run: jq --arg value "test" '.variable[0].value=$value' products-service.postman_collection.json | sponge products-service.postman_collection.json

    - name: Read Collection
      run: cat products-service.postman_collection.json

    - name: Run POSTMAN collection
      run: |
        newman run "products-service.postman_collection.json" -r htmlextra --reporter-htmlextra-export result/report.html

    - name: Output the run Details
      uses: actions/upload-artifact@v3
      with:
        name: Reports
        path: result