name: Postman testing

on:
  workflow_call:

jobs:
  postman-testing:
    name: Postman testing
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Run Docker compose
      run: docker-compose -f "docker-compose.yaml" up -d

    - name: Sleep for 30 seconds
      run: sleep 30s
      shell: bash

    - name: Ps
      run: docker ps
    
    - name: Logs
      run: docker logs postman-tests-container

    - name: Output the run Details
      uses: actions/upload-artifact@v3
      with:
        name: Reports
        path: postman/reports/

    - name: Clean Up Containers
      run: docker-compose down