name: Release pipeline

on:
  push:
    branches:
      - 'develop'
      - 'staging'
      - 'main'

jobs:
  build-and-analyze:
    uses: ./.github/workflows/build-and-analyze.yaml

  docker-push:
    runs-on: ubuntu-latest
    needs: build-and-analyze
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/products-service:latest
